Another quotation fix in the converter app

diff --git a/editor/tools/Playdate Asset Converter.app/Contents/Resources/script b/editor/tools/Playdate Asset Converter.app/Contents/Resources/script
--- a/editor/tools/Playdate Asset Converter.app/Contents/Resources/script
+++ b/editor/tools/Playdate Asset Converter.app/Contents/Resources/script
@@ -81,10 +81,10 @@ rm "$TEMP_DESTINATION_DIR/pdxinfo"
 
 if [ -f "$INPUT" ]; then
   # we know this will be 1 file
-  mv "$TEMP_DESTINATION_DIR"/* "$DESTINATION_DIR" || { echo "Failed to move files"; exit 1; }
+  mv "$TEMP_DESTINATION_DIR"/* "$DESTINATION_DIR" || { echo "Failed to move file"; exit 1; }
 else
   # we know this will be a directory
-  cp -r $TEMP_DESTINATION_DIR/* "$DESTINATION_DIR" || { echo "Failed to move files"; exit 1; }
+  cp -r "$TEMP_DESTINATION_DIR"/* "$DESTINATION_DIR/" || { echo "Failed to move files"; exit 1; }
 fi
 
 echo "Removing the temp output directory"
